name: hospital_occupancy_tracker
## !!! renv.lock file must be in directory !!!

## script runs around 1pm local time
on:
  schedule:
  - cron: 0 16 * * *
  
## run script on push
#on: push

jobs:
  get-data-from-csv:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      
      # setup R and packages 
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      # reads renv file for packages
      - uses: r-lib/actions/setup-renv@v2
      - run: Rscript script.R

     # add file to data folder, commit, push
      - name: commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/* img/*
          git commit -am "Scheduled Github Action on $(date)"
          git push origin main
        
